"""posts table

Revision ID: 37096716a708
Revises: 
Create Date: 2019-04-15 18:30:22.861000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37096716a708'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('post', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_post'), 'post', ['post'], unique=False)
    op.create_index(op.f('ix_post_time'), 'post', ['time'], unique=False)
    op.create_index(op.f('ix_post_username'), 'post', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_username'), table_name='post')
    op.drop_index(op.f('ix_post_time'), table_name='post')
    op.drop_index(op.f('ix_post_post'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
