"""updated unique key

Revision ID: f4f1b0566c47
Revises: 37096716a708
Create Date: 2019-04-15 18:37:44.097000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f1b0566c47'
down_revision = '37096716a708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_username', table_name='post')
    op.create_index(op.f('ix_post_username'), 'post', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_username'), table_name='post')
    op.create_index('ix_post_username', 'post', ['username'], unique=1)
    # ### end Alembic commands ###
